### ISSUE TITLE
tasks too complicated

### ISSUE THREAD

**Issue by jeffnv** [fndelacruz/RoboTask#3]
No one will make a task if they have to fill in all those fields! Is assigned doesn't need to be a column, we should be able to look that up using the join table which joins a robot to a task!

**Comment by jeffnv** [comment]
also, initially, I would simplify. a task should just be a description, start date, and end date. All that other stuff is just extra adornment of the fundamental concept

**Comment by fndelacruz** [comment]
Thanks for the suggestion- I caught a couple other redundant columns that can be determined via join tables. I think my base schema looks a bit cleaner now.

Good idea- I will initially start with a task description, start and end date. I see now that the TaskType and Qualifications are just variations of a "task detail", ex: "start/end date". I'll consider adding them later depending on project timing
