### ISSUE TITLE
schema needs rethinking

### ISSUE THREAD

**Issue by jeffnv** [fndelacruz/RoboTask#4]
please see a TA and work on a revised schema

**Comment by fndelacruz** [comment]
Overhauled my db schema. I limited the basic schema to 4 Models: Users, Tasks, Timeslices (start/end dates, belongs_to worker_Users and Tasks), and Task Reviews. I deleted redundant columns (logic that can be determined via join tables). I think it looks much more reasonable now. Will check in with another TA for a second look. Thanks for the tips!
